### ISSUE TITLE
WARN Codegen didn't run for RNCTabView on RN 0.75.4 and RNBT 0.1.2

### ISSUE THREAD

**Issue by shovel-kun** [okwasniewski/react-native-bottom-tabs#87] opened 2024-10-29 00:04 UTC
Here's the warning:

```
 (NOBRIDGE) WARN  Codegen didn't run for RNCTabView. This will be an error in the future. Make sure you are using @react-native/babel-preset when building your JavaScript code.
 ```
 
The bottom tab fails to render on Android (have not test on iOS).
 
Adding `module:@react-native/babel-preset` to my babel config (after removing `babel-preset-expo` from presets and rebuilding) has no effect.

Don't have a repro atm. Just reporting in case anyone else also has the same problem.

my babel preset can be seen below:
```js
const ReactCompilerConfig = {
  target: "18", // '17' | '18' | '19'
  runtimeModule: "react-compiler-runtime",
};

/** @type {import('@babel/core').TransformOptions} */
module.exports = function (api) {
  api.cache(true);
  return {
    presets: [
      // ["babel-preset-expo", { jsxImportSource: "nativewind" }],
      ["module:@react-native/babel-preset"],
      "nativewind/babel",
    ],
    env: {
      production: {},
    },
    plugins: [
      // https://react.dev/learn/react-compiler
      // Should come first
      ["babel-plugin-react-compiler", ReactCompilerConfig],
      ["react-native-reanimated/plugin"],
      [
        "module-resolver",
        {
          root: ["./"],
          alias: {
            "@": "./",
          },
        },
      ],
    ],
  };
};
```

**Comment by Vijayabaskar56** [comment] 2024-10-29 02:15
I am also Facing the Same Issue
![Screenshot_2024-10-29-07-40-24_1920x1080](https://github.com/user-attachments/assets/066c600c-f110-4d32-b640-d2e2e46f17ff)

**Comment by douglowder** [comment] 2024-10-29 03:14
Same here. The problem does not occur on iOS or tvOS. This happens when new arch is enabled.

When new arch disabled, I see a different error, this one when updating the "items" property in the module.

**Comment by okwasniewski** [comment] 2024-10-29 10:24
Hey, can you try with version 0.1.4?

**Comment by shovel-kun** [comment] 2024-10-29 12:28
@okwasniewski 

The tab bar renders along with icons!

However, it seems like labels only render for initial frame before disappearing. When `labeled={true}`, all labels render and then disappear. When undefined, the current active tab renders label for a frame, and then never again. The rest of the (inactive) tabBarLabels do not render any labels, and when they become active they don't render label.

**Comment by okwasniewski** [comment] 2024-10-29 12:37
> @okwasniewski
> 
> The tab bar renders along with icons!
> 
> However, it seems like labels only render for initial frame before disappearing. When `labeled={true}`, all labels render and then disappear. When undefined, the current active tab renders label for a frame, and then never again. The rest of the (inactive) tabBarLabels do not render any labels, and when they become active they don't render any label, leaving empty space where they should've rendered.
> 


Can you try Changing the `styles.xml`? You can use this expo config plugin: https://github.com/okwasniewski/react-native-bottom-tabs/discussions/75

Or change it in Android Studio, https://okwasniewski.github.io/react-native-bottom-tabs/docs/guides/android-native-styling.html

The Material3 style will be the default once I get expo config plugin working inside of the package.



> BTW, typehinting for `createNativeBottomTabNavigator()` is broken on React Navigation v7.

Thanks for checking it out, this needs a separate issue.

**Comment by shovel-kun** [comment] 2024-10-29 12:45
While the styles do apply from `<style name="AppTheme" parent="Theme.MaterialComponents.DayNight.NoActionBar">` and `<style name="AppTheme" parent="Theme.Material3.DayNight.NoActionBar">`, the label still fails to render. 

![image](https://github.com/user-attachments/assets/86cf6bdf-aea5-4b92-ad77-06bc7562dafa)

Code
```ts
const HomeTabs = createNativeBottomTabNavigator<BottomNavigatorParamList>();

function HomeTabsNavigator() {
  const { t } = useTranslation();
  return (
    <HomeTabs.Navigator
      tabBarInactiveTintColor="#C57B57"
      tabBarActiveTintColor="#F7DBA7"
      barTintColor="#1E2D2F"
      rippleColor="#F7DBA7"
      activeIndicatorColor="#041F1E"
    >
      <HomeTabs.Screen
        name="Library"
        component={LibraryTopTabNavigator}
        options={{
          title: t("label.library"),
          tabBarLabel: "Library",
          tabBarIcon: () => require("../../assets/images/react-logo.png"),
        }}
      />
      <HomeTabs.Screen
        name="General"
        component={GeneralScreen}
        options={{
          title: t("label.general"),
          tabBarLabel: "Library",
          tabBarIcon: () => require("../../assets/images/react-logo.png"),
        }}
      />
      <HomeTabs.Screen
        name="Updates"
        component={UpdatesScreen}
        options={{
          title: t("label.updates"),
          tabBarLabel: "Library",
          tabBarIcon: () => require("../../assets/images/react-logo.png"),
        }}
      />
      <HomeTabs.Screen
        name="Browse"
        component={BrowseTopTabNavigator}
        options={{
          title: t("label.browse"),
          tabBarIcon: () => require("../../assets/images/react-logo.png"),
        }}
      />
      <HomeTabs.Screen
        name="More"
        // On iOS, we put the MoreStack in the Bottom Tabs navigator
        component={Platform.OS === "ios" ? MoreStackNavigator : MoreScreen}
        options={{
          title: t("label.more"),
          tabBarIcon: () => require("../../assets/images/react-logo.png"),
        }}
      />
    </HomeTabs.Navigator>
  );
}
```

Are you able to repro?

I'll open a new one.

**Comment by okwasniewski** [comment] 2024-10-29 13:12
@shovel-kun Interesting.. I couldn't repro this. Can you create a minimal example app where this occurs? Would be really helpful 🙏

**Comment by okwasniewski** [comment] 2024-10-29 13:32
For people that encounter this issue in the future, can we move the rendering issue to a separate one? This will make it easier to search among issues. 

The issue with "Codegen didn't run.." is fixed, I'll close this one. Can you please open a new issue with a repro @shovel-kun for the issue you are having?

**Closed by okwasniewski** 2024-10-29 13:32 UTC
Labels: bug, Android

**Comment by shovel-kun** [comment] 2024-10-30 11:45
@okwasniewski

Found the issue. It was actually related to `react-native-edge-to-edge`. It seems that even if I had `<style name="AppTheme" parent="Theme.Material3.DayNight.NoActionBar">
`set in `styles.xml` and didn't set an expo-plugin for `react-native-edge-to-edge`, it will still force edge-to-edge, causing navigation bar to overlay the native bottom tabs and thus causing some miscalculations in the code, I presume. Had to completely uninstall it to stop edge-to-edge behaviour.

Not sure if this is something that can be resolved on `react-native-bottom-tabs` end.

**Comment by okwasniewski** [comment] 2024-10-30 12:01
> ations in the code, I presu

I'm happy that you found the root cause @shovel-kun, I'm not sure if this can be handled on bottom-tabs side, technically native views should adapt automatically.. I've created a feature request in the edge-to-edge repo to add additional styles: https://github.com/zoontek/react-native-edge-to-edge/issues/38

@zoontek do you know if there is anything special I should do to handle edge-to-edge?

**Comment by shovel-kun** [comment] 2024-10-30 13:10
Btw to replicate go to `example`, `yarn add react-native-edge-to-edge`, and then build and run. 

Result:
![image](https://github.com/user-attachments/assets/b6f8217d-f81a-4081-b0a4-7d8689cd819e)

**Comment by zoontek** [comment] 2024-10-30 14:49
@okwasniewski I will have a look, but I think there's no need for an adaptation of `react-native-bottom-tabs`. `react-native-edge-to-edge` use [textbook implementation](https://developer.android.com/develop/ui/views/layout/edge-to-edge-manually), so this is probably just a question of additional themes.

**Comment by zoontek** [comment] 2024-10-30 18:22
@shovel-kun Following this: https://github.com/okwasniewski/react-native-bottom-tabs/issues/97
