### ISSUE TITLE
Lucide / SVG icons

### ISSUE THREAD

**Issue by gunnartorfis** [okwasniewski/react-native-bottom-tabs#114] opened 2024-11-03 12:00 UTC
Just noticed that documentation has been added for vector icons. 
Is it possible to use Lucide/SVG icons?

**Comment by bacarybruno** [comment] 2024-11-03 17:00
+1 for this, specially because [expo/vector-icons](https://github.com/expo/vector-icons?tab=readme-ov-file#expovector-icons) doesn't expose / support getImageSource.

**Comment by okwasniewski** [comment] 2024-11-03 17:12
Hey, 

Thanks for opening the issue. 

At this point it's not possible. You can't pass custom React Native component into the tab bar because of native limitations so this won't be supported (Lucide only supports icon components). 

Regarding SVG Icons I'm looking into adding support for this but at this point Im using same functionality that React Native Core is using to load Images in the <Image /> component, handing SVGs would require going custom. 

Regarding `expo/vector-icons`, you can read more about this library here: https://twitter.com/notbrent/status/1851718411128041714 (It's going to be deprecated soon). 

Most of the icons for the tab bar _should_ be static so if possible I would suggest getting them as static assets and using them as usual

**Closed** 2024-11-11 16:42 UTC
Labels: enhancement

**Comment by afkcodes** [comment] 2024-12-17 15:32
the svgs look blurry if supplied externally @okwasniewski  did you face this ?

**Comment by okwasniewski** [comment] 2024-12-17 17:58
@afkcodes There shouldn't be any degradation if they are external - can you open an issue with reproduction?
