### ISSUE TITLE
(iOS) Scrollbar is offset by approx 30px

### ISSUE THREAD

**Issue by dylancom** [okwasniewski/react-native-bottom-tabs#49] opened 2024-10-15 08:23 UTC
The scrollbar is offset approx 30px. The content isn't offset but the bar on the right for some reason.
AFAIK it should touch the top?

<img src="https://github.com/user-attachments/assets/b3d4016c-5922-40cf-9d26-d7f2b19dfd86" width="300" />

**Comment by okwasniewski** [comment] 2024-10-15 09:45
Interesting... setting `automaticallyAdjustsScrollIndicatorInsets={false}` on ScrollView fixes this 😅

**Comment by dylancom** [comment] 2024-10-15 10:00
Interesting indeed! Maybe because insets are set manually?

**Comment by dylancom** [comment] 2024-10-17 18:46
Related error: https://stackoverflow.com/questions/78219733/how-to-fix-incorrect-scroll-indicator-inset-in-swiftui

**Comment by okwasniewski** [comment] 2024-11-06 08:06
@dylancom It looks like this is only happening in the example repo case where we have a Stack that embeds a bunch of Bottom-Tab Navigators. Most of the time (and it's recommended), people should use Tabs as the root navigator (or use stack without header) and then embed the stack in each tab for navigation. 

And this case works flawlessly: 

https://github.com/user-attachments/assets/7cc72649-a9c8-4d32-8f78-68e1570e723c

I will close this issue as I think automatic adjustment was designed with this in mind.

**Closed by okwasniewski** 2024-11-06 08:06 UTC
Labels: bug, iOS

**Comment by dylancom** [comment] 2024-11-06 08:15
Oke so it should work properly if you has a "RootStack" with 2 groups? One for your Tabs and one group for your modals? As advised by React Navigation.

**Comment by okwasniewski** [comment] 2024-11-06 08:35
> Oke so it should work properly if you has a "RootStack" with 2 groups? One for your Tabs and one group for your modals? As advised by React Navigation.

Yeah, this should be possible and work correctly:

- RootStack (headerShown:false) 
- TabNavigator
  - Tab1Stack (headerShown: true)
  - Tab2Stack (headerShown: true)
- Modals

**Comment by dylancom** [comment] 2024-11-06 08:44
Awesome, then this can be closed indeed. Have only tested the lib yet from the example app.
